IF OBJECT_ID(N'dbo.Midnight') IS NOT NULL
  DROP FUNCTION dbo.Midnight
GO

CREATE FUNCTION dbo.Midnight(
	@Date DATETIME
)
RETURNS DATETIME
AS
BEGIN
	RETURN CAST(CAST(@Date AS DATE) AS DATETIME)
END


