SELECT T1.ColumnName, T2.ColumnName

FROM
(
	SELECT
		S.name AS SchemaName
	,	T.name AS TableName
	,	C.name AS ColumnName
	,	TP.name AS TypeName
	,	C.max_length AS TypeLength
	,	C.[precision] AS TypePrecision
	,	C.scale AS TypeScale
	,	C.is_nullable AS ColumnIsNullable
	,	C.column_id AS ColumnCardinalLocation
	,	C.is_identity AS ColumnIsIdentity
	FROM
				sys.tables	T
	INNER JOIN	sys.columns	C	ON	T.object_id = C.object_id
	INNER JOIN	sys.types	TP	ON	C.user_type_id = TP.user_type_id
	INNER JOIN	sys.schemas	S	ON	T.schema_id = S.schema_id
	WHERE
		T.name = 'SHL201A'
)	T1
FULL JOIN
(
	SELECT
		S.name AS SchemaName
	,	T.name AS TableName
	,	C.name AS ColumnName
	,	TP.name AS TypeName
	,	C.max_length AS TypeLength
	,	C.[precision] AS TypePrecision
	,	C.scale AS TypeScale
	,	C.is_nullable AS ColumnIsNullable
	,	C.column_id AS ColumnCardinalLocation
	,	C.is_identity AS ColumnIsIdentity
	FROM
				sys.tables	T
	INNER JOIN	sys.columns	C	ON	T.object_id = C.object_id
	INNER JOIN	sys.types	TP	ON	C.user_type_id = TP.user_type_id
	INNER JOIN	sys.schemas	S	ON	T.schema_id = S.schema_id
	WHERE
		T.name = 'SHP201'
)	T2	ON	T1.ColumnName = T2.ColumnName
;


SELECT ITITCD, ITCORG, ITSTATUS, ITCIST, ITSIST, ITITDS, ITUOM, ITUWT, ITSTSBCLCD, ITSTSBCLDS, ITSTCLCD, ITSTCLDS, ITSTGRCD, ITSTGRDS, ITSTTYCD, ITSTTYDS, ITPTCD, ITPTDS, ITVSEQNO, ITFOCFL, ITIRG1CD, ITIRG1DS, ITMKCD, ITMKDS, ITMKSPCD, ITMKSPNM, ITMKBKCD, ITMKBKNM, ITTFEXCD, ITTFCLCD, ITTFCGCD, ITMKOVRT, ITSDOVRT, ITEXDMFL, ITREALFL, ITPRGPCD, ITCAT2CD, ITCAT2DS, ITCAT3CD, ITCAT3DS, ITCAT4CD, ITCAT4DS, ITSLFZFL, ITBGITFL, ITBGPPFL, ITCOMFL, ITCNTSTFL, ITITMACT, ITGLSUB, ITGRNWT, ITSYRT, ITPYRT, ITLRCD, ITCMPGDS, ITMPRFL
FROM [PORK\erick].[SHP201]

EXCEPT

SELECT ITITCD, ITCORG, ITSTATUS, ITCIST, ITSIST, ITITDS, ITUOM, ITUWT, ITSTSBCLCD, ITSTSBCLDS, ITSTCLCD, ITSTCLDS, ITSTGRCD, ITSTGRDS, ITSTTYCD, ITSTTYDS, ITPTCD, ITPTDS, ITVSEQNO, ITFOCFL, ITIRG1CD, ITIRG1DS, ITMKCD, ITMKDS, ITMKSPCD, ITMKSPNM, ITMKBKCD, ITMKBKNM, ITTFEXCD, ITTFCLCD, ITTFCGCD, ITMKOVRT, ITSDOVRT, ITEXDMFL, ITREALFL, ITPRGPCD, ITCAT2CD, ITCAT2DS, ITCAT3CD, ITCAT3DS, ITCAT4CD, ITCAT4DS, ITSLFZFL, ITBGITFL, ITBGPPFL, ITCOMFL, ITCNTSTFL, ITITMACT, ITGLSUB, ITGRNWT, ITSYRT, ITPYRT, ITLRCD, ITCMPGDS, ITMPRFL
FROM [PORK\erick].[SHL201A]


SELECT ITITCD, ITCORG, ITSTATUS, ITCIST, ITSIST, ITITDS, ITUOM, ITUWT, ITSTSBCLCD, ITSTSBCLDS, ITSTCLCD, ITSTCLDS, ITSTGRCD, ITSTGRDS, ITSTTYCD, ITSTTYDS, ITPTCD, ITPTDS, ITVSEQNO, ITFOCFL, ITIRG1CD, ITIRG1DS, ITMKCD, ITMKDS, ITMKSPCD, ITMKSPNM, ITMKBKCD, ITMKBKNM, ITTFEXCD, ITTFCLCD, ITTFCGCD, ITMKOVRT, ITSDOVRT, ITEXDMFL, ITREALFL, ITPRGPCD, ITCAT2CD, ITCAT2DS, ITCAT3CD, ITCAT3DS, ITCAT4CD, ITCAT4DS, ITSLFZFL, ITBGITFL, ITBGPPFL, ITCOMFL, ITCNTSTFL, ITITMACT, ITGLSUB, ITGRNWT, ITSYRT, ITPYRT, ITLRCD, ITCMPGDS, ITMPRFL
FROM [PORK\erick].[SHL201A]

EXCEPT

SELECT ITITCD, ITCORG, ITSTATUS, ITCIST, ITSIST, ITITDS, ITUOM, ITUWT, ITSTSBCLCD, ITSTSBCLDS, ITSTCLCD, ITSTCLDS, ITSTGRCD, ITSTGRDS, ITSTTYCD, ITSTTYDS, ITPTCD, ITPTDS, ITVSEQNO, ITFOCFL, ITIRG1CD, ITIRG1DS, ITMKCD, ITMKDS, ITMKSPCD, ITMKSPNM, ITMKBKCD, ITMKBKNM, ITTFEXCD, ITTFCLCD, ITTFCGCD, ITMKOVRT, ITSDOVRT, ITEXDMFL, ITREALFL, ITPRGPCD, ITCAT2CD, ITCAT2DS, ITCAT3CD, ITCAT3DS, ITCAT4CD, ITCAT4DS, ITSLFZFL, ITBGITFL, ITBGPPFL, ITCOMFL, ITCNTSTFL, ITITMACT, ITGLSUB, ITGRNWT, ITSYRT, ITPYRT, ITLRCD, ITCMPGDS, ITMPRFL
FROM [PORK\erick].[SHP201]